* My Emacs Configuration
** Windows Install
*** Prerequisites
This configuration use el-get as package manager, so it needs the following applications to be include in the system PATH variable:
+ git http://git-scm.com/downloads
+ texinfo http://gnuwin32.sourceforge.net/packages/texinfo.htm
And these DLL's copied in the %EMACS_APP_ABSOLUTE_DIRECTORY_PATH%\bin:
+ GNU TLS http://www.gnu.org/software/emacs/manual/html_mono/emacs-gnutls.html#Help-For-Users
*** Shell Integration
+ Modify Add-Emacs-To-Open-Any-File.reg file setting your %EMACS_APP_ABSOLUTE_DIRECTORY_PATH%
+ Execute the modified Windows Register file
*** Emacs Home Variable
While you’re here, you might as well set your Home variable. This is what Emacs will use whenever you refer to ~, or the home directory. To set that, look under User variables and click on New. Create a variable called HOME, and set the value to whichever directory you would like to use as your home directory.
*** Pin Emacs in the Task Bar
Want to be able to start up and switch to Emacs quickly? To pin Emacs to your task bar:
+ Right-click on the Emacs icon in the task bar.
+ Right-click on the small Emacs icon that appears, and click on Properties.
+ Change the target to %EMACS_APP_ABSOLUTE_DIRECTORY_PATH%\bin\runemacs.exe, and change the start directory to whichever directory you prefer. You can also choose to start it maximized – handy.
+ Once you’ve set that up, click OK.
I like dragging the Emacs icon so that it’s the very first item in my task bar. That way, pressing the Windows key and the number 1 at the same time lets me switch to Emacs and away from Emacs easily.
